using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;
using DataLayer.Annotations;

namespace DataLayer.Model
{
    //todo farouk
    /* 
     * the notifications will be shown on the application sidebar, 
     * some notifications are autogenerated (and inserted inside the notification Table in the db) using a Trigger or something, 
     * for example "l'sms de confirmation n'a pas encore etais envoyer au [Nom patint]", the app will access this table periodicly by setting a timer...
     * 
     * some notification arn't inserted in the database, they are generated by code and they are informative or general warnnings mostly
     * for example "le patient [] a été inserer avec succes"
     * 
     *          
     */

    public enum TypeNotification
    {
        Information=1,
        Warnning=2,
        Reminder=3,
        Critical=4
    }
    public class Notification:INotifyPropertyChanged
    {
        #region Fields
        
        #endregion
        #region Properties
        public Guid NotificationId { get; set; }
        public String NotificationTitle { get; set; }
        public TypeNotification NotificationType { get; set; }
        public TypeNotification NotificationMessage { get; set; }
        
        #endregion
        #region INotifyPropertyChanged Related logic                
        public event PropertyChangedEventHandler PropertyChanged;

        [NotifyPropertyChangedInvocator]
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));
        }
        #endregion
    }
}
