using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;
using DataLayer.Annotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using DataLayer.Attributes;

namespace DataLayer.Model
{
    //todo farouk
    /* 
     * the notifications will be shown on the application sidebar, 
     * some notifications are autogenerated (and inserted inside the notification Table in the db) using a Trigger or something, 
     * for example "l'sms de confirmation n'a pas encore etais envoyer au [Nom patint]", the app will access this table periodicly by setting a timer...
     * 
     * some notification arn't inserted in the database, they are generated by code and they are informative or general warnnings mostly
     * for example "le patient [] a été inserer avec succes"
     * 
     *          
     */

    [Table("Notifications")]
    public class Notification : INotifyPropertyChanged
    {
        

        #region Fields
        private string _notificationTitle;
        private TypeNotification _notificationType;
        private string _notificationMessage;
        private byte[] _image;

        #endregion

        #region Properties
        public Guid NotificationId { get; set; }

        [MaxLength(128)]
        [Search]
        public String NotificationTitle
        {
            get { return _notificationTitle; }
            set
            {
                if (value == _notificationTitle) return;
                _notificationTitle = value;
                OnPropertyChanged();
            }
        }

        public TypeNotification NotificationType
        {
            get { return _notificationType; }
            set
            {
                if (value == _notificationType) return;
                _notificationType = value;
                OnPropertyChanged();
            }
        }

        [MaxLength(1024)]
        [Search]
        public String NotificationMessage   
        {
            get { return _notificationMessage; }
            set
            {
                if (value == _notificationMessage) return;
                _notificationMessage = value;
                OnPropertyChanged();
            }
        }

        [NotMapped]
        public Byte[] Image
        {
            get { return _image; }
            set
            {
                if (Equals(value, _image)) return;
                _image = value;
                OnPropertyChanged();
            }
        }
        [NotMapped]
        public int Id { get; set; }  //this is used to handle local and only local notifications


        public Guid? NotifyUserId { get; set; }
        public TypeUser TypeUser { get; set; }        
        public DateTime CreatedOn { get; set; }
        public DateTime ModifiedOn { get; set; }
        public bool IsSystem { get; set; }
        public bool IsActive { get; set; }

        #endregion

        #region INotifyPropertyChanged Related logic
        public event PropertyChangedEventHandler PropertyChanged;

        [NotifyPropertyChangedInvocator]
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));
        }
        #endregion
    }
}
