//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPMCAppointmentSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WindowStaticText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WindowStaticText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPMCAppointmentSystem.Resources.WindowStaticText", typeof(WindowStaticText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments System.
        /// </summary>
        public static string Login_ApplicationTitleLabel {
            get {
                return ResourceManager.GetString("Login_ApplicationTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string Login_ConnectionButton {
            get {
                return ResourceManager.GetString("Login_ConnectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log-In.
        /// </summary>
        public static string Login_LoginLabel {
            get {
                return ResourceManager.GetString("Login_LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        public static string Login_UserNameWaterMark {
            get {
                return ResourceManager.GetString("Login_UserNameWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string Login_UserPassWaterMark {
            get {
                return ResourceManager.GetString("Login_UserPassWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medecins.
        /// </summary>
        public static string MainView_DoctorsLabel {
            get {
                return ResourceManager.GetString("MainView_DoctorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string MainView_LogLabel {
            get {
                return ResourceManager.GetString("MainView_LogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes Patients.
        /// </summary>
        public static string MainView_MyPatientLabel {
            get {
                return ResourceManager.GetString("MainView_MyPatientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string MainView_NotificationsLabel {
            get {
                return ResourceManager.GetString("MainView_NotificationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathologies.
        /// </summary>
        public static string MainView_PathologiesLabel {
            get {
                return ResourceManager.GetString("MainView_PathologiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string MainView_PatientsLabel {
            get {
                return ResourceManager.GetString("MainView_PatientsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planificateur.
        /// </summary>
        public static string MainView_PlanificateurLabel {
            get {
                return ResourceManager.GetString("MainView_PlanificateurLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        public static string MainView_SettingsLabel {
            get {
                return ResourceManager.GetString("MainView_SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spécialités.
        /// </summary>
        public static string MainView_SpecialityLabel {
            get {
                return ResourceManager.GetString("MainView_SpecialityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiques.
        /// </summary>
        public static string MainView_StatistiquesLabel {
            get {
                return ResourceManager.GetString("MainView_StatistiquesLabel", resourceCulture);
            }
        }
    }
}
